spring.application.name=homeFinance
server.port=8080
server.servlet.context-path=/api/v1
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create-drop
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:db.changelog/db.changelog-master.xml
jwt.secret=Zk3w9fG$7k@vBn4!sLpT8dQcYzR2x#MmXe9VuKaFtH0gNs1jCq
jwt.expiration=3600000
springdoc.api-docs.path=/doc/v3/api-docs
springdoc.swagger-ui.path=/doc/swagger-ui.html
